### ISSUE TITLE
Background music only plays on level 1

### ISSUE THREAD

**Issue by zachseidner1** [zachseidner1/death-of-a-deal#101]

**Comment by PeterXuannanWu** [comment]
This can be fixed with adding the "bgm" field to all existing levels. Except for level3.json, which also didn't have the background field in it. 26b1a40

**Comment by PeterXuannanWu** [comment]
@zachseidner1

**Comment by zachseidner1** [comment]
Are you refactoring this to use Tiled map properties?

**Comment by zachseidner1** [comment]
This was refactored
