### ISSUE TITLE
Memory overflow when staying on Level Select Screen [Critical]

### ISSUE THREAD

**Issue by PeterXuannanWu** [zachseidner1/death-of-a-deal#102]
Memory overflows to up to 40 GB (limit before my laptop crashes) when staying too long on the level select menu (around 10 minutes). Could be related to infinite background generation? Needs detailed memory allocation check with IntelliJ

@zachseidner1

**Comment by zachseidner1** [comment]
Should be resolved by eb1f645e35503467f1314b7e65df00b565fa1dc1
