### ISSUE TITLE
Spinner Initialization offset

### ISSUE THREAD

**Issue by PeterXuannanWu** [zachseidner1/death-of-a-deal#43]
<img width="758" alt="image" src="https://github.com/zachseidner1/death-of-a-deal/assets/125776583/f62cea47-c2f0-457d-9c52-7e557641b8e7">
As seen here an additional piece of code is needed here in tileParseJson to deal with the spinner platform class. It could be something related to the pivot point being different in tiled and box2d. The current version works but might need changes for consistency in the future.

**Comment by zachseidner1** [comment]
This was fixed in 7d3affcbacc7fc155b85010b0a9ae92006ad21f3
