### ISSUE TITLE
Miss match between tiled texture and rendered game

### ISSUE THREAD

**Issue by PeterXuannanWu** [zachseidner1/death-of-a-deal#57]
For wood texture, if you choose the vertical edges you will actually get another texture, as shown below.

<img width="912" alt="image" src="https://github.com/zachseidner1/death-of-a-deal/assets/125776583/0f9423a6-7ab9-4971-95ce-cddfb5e3caa8">
<img width="1552" alt="image" src="https://github.com/zachseidner1/death-of-a-deal/assets/125776583/62810cef-7b55-41e5-9009-e9d7c42d60e9">

**Comment by zachseidner1** [comment]
I don't think this is an issue anymore.
