### ISSUE TITLE
Jumping animation seems to only play when the player hits the ground

### ISSUE THREAD

**Issue by zachseidner1** [zachseidner1/death-of-a-deal#70]
Try jumping in game to reproduce. I don't think this is intended right?

**Comment by PeterXuannanWu** [comment]
I am pretty sure that the animation is playing when the player hits the jump button. It is just that the animation is twice as long as walking animation, and plays very slow. I just double-checked and it is working as intended, as you can find proof in the video below.

https://github.com/zachseidner1/death-of-a-deal/assets/125776583/3b956278-a550-4191-b3fd-3daf80cfb595
